name: todo2_sdk
version: 0.0.1

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  messaging_sdk:
    hosted:
      name: messaging_sdk
      url: https://pub.workiva.org
    version: ^3.5.4
  todo_transport:
    git:
      url: git@github.com:thomasmaloney-wk/todo2-transport.git
  uuid: ">=1.0.3 <2.0.0"
  w_session:
    hosted:
      name: w_session
      url: https://pub.workiva.org
    version: ^6.68.0

dev_dependencies:
  dart_dev: ^3.2.1
  dart_style: ^1.3.3
  test: ^1.8.0